config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :tasks, except: [:show, :new] do
    member do
      patch :good
    end
  end
  get '/time' => 'tasks#time'
  get '/every' => 'tasks#every'
  get '/todo' => 'tasks#todo'
  get '/by_chance' => 'tasks#by_chance'
  # delete '/destroy_all' => 'tasks#destroy_all'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :sentence, presence: true

  enum category: { "時間が決まったタスク":0,"よく使うタスク":1,"たまたま行ったタスク":2,"ToDo":3 }

  def set_time
  Task.time.strftime("%-H:%M")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html {
          if @task.category == "時間が決まったタスク"
            redirect_to time_path
          elsif @task.category == "よく使うタスク"
            redirect_to every_path
          elsif @task.category == "たまたま行ったタスク"
            redirect_to by_chance_path
          elsif @task.category == "ToDo"
            redirect_to todo_path
          else
            render :root
          end
        }
        format.json { render :time, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { if @task.category == "時間が決まったタスク"
                        redirect_to time_path
                      elsif @task.category == "よく使うタスク"
                        redirect_to every_path
                      elsif @task.category == "たまたま行ったタスク"
                        redirect_to by_chance_path
                      elsif @task.category == "ToDo"
                        redirect_to todo_path
                      else
                        render :root
                      end }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { if @task.category == "時間が決まったタスク"
                        redirect_to time_path
                      elsif @task.category == "よく使うタスク"
                        redirect_to every_path
                      elsif @task.category == "たまたま行ったタスク"
                        redirect_to by_chance_path
                      elsif @task.category == "ToDo"
                        redirect_to todo_path
                      else
                        render :root
                      end }
      format.json { head :no_content }
    end
  end

  # def destroy_all
  #   Task.destroy_all
  #   respond_to do |format|
  #     format.html { if Task.category == "時間が決まったタスク"
  #                       redirect_to time_path
  #                     elsif Task.category == "よく使うタスク"
  #                       redirect_to every_path
  #                     elsif Task.category == "たまたま行ったタスク"
  #                       redirect_to by_chance_path
  #                     elsif Task.category == "ToDo"
  #                       redirect_to todo_path
  #                     else
  #                       render :root
  #                     end }
  #     format.json { head :no_content }
  #   end
  # end

  def time
    @task = Task.new
    @tasks = Task.where(category:0).order(:time)
    p @tasks
  end

  def every
    @task = Task.new
    @tasks = Task.where(category:1)
  end

  def todo
    @task = Task.new
    @tasks = Task.where(category:3)
  end

  def by_chance
    @task = Task.new
    @tasks = Task.where(category:2)
  end

#カウントアップ機能
  def good
    @task = Task.find(params[:id])
    @task.increment!(:good, 1)
    redirect_to :time
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def task_params
    #   params.fetch(:task, {})
    # end

    def task_params
      params.require(:task).permit(:sentence, :category, :good, :time,)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/homes/top.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="heading">習慣化で理想のライフスタイルを</div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-auto">
    <p>習慣化とは、同じ状況のもとで繰り返し行われた行動がやがて定着し、（意志とは関係なく）自動化されて行われることです。<br>
       習慣化には、人生そのものを大きく変える力があります。習慣化のテクニックがあれば、自分が思うように生きることが可能になるでしょう。<br>
      しかし、実際には習慣化が苦手で、挫折してかえってつらい思いをしている人が後を絶ちません。本当にもったいないことです。<br>
      そこでこのアプリケーションでは、思い通りの人生を実現するために欠かせない「習慣化」を、手助けするために開発されました。</p>
    </div>
  </div>
      <p>使い方は簡単です</p>
      <div class = "box">
        <div class="step">Step 1</div>
      <div>タスク内容の入力</div>
        
      </div>
      <div class = "box">
              <div class="step">Step 2</div>
      <div>タスクの種類を選択</div>

      </div>
      <div class = "box">
              <div class="step">Step 3</div>
      <div>クリエイトボタンをクリック</div>

      </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to"ロゴ", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to "よくやるtask", every_path, class: 'nav-link text-dark'%>
        </li>
        <li>
          <%= link_to "時間が決まったtask", time_path, class: 'nav-link text-dark' %>
        </li>
        <li>
          <%= link_to "たまたまやったtask", by_chance_path, class: 'nav-link text-dark' %>
        </li>
        <li>
          <%= link_to "ToDo", todo_path, class: 'nav-link text-dark' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <%= render 'layouts/header' %>
      

    </header>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: 'js-form') do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class: 'form-group'>
    <%= f.text_area :sentence %>
    </div>
    <select name="task[category]" id="task_category">
      <option value="">選択してください</option>
      <option value="時間が決まったタスク">時間が決まったタスク</option>
      <option value="よく使うタスク">よく使うタスク</option>
      <option value="たまたま行ったタスク">たまたま行ったタスク</option>
      <option value="ToDo">ToDo</option>
    </select>
    <%= f.time_field :time, class: "time" %>
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_index.html.erb
あなたの今日のグッジョブは<%= Task.all.sum(:good) %>グッジョブです！

<table id="js-table-index" class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <!--<#%= link_to "全て削除",destroy_all_path,  method: :delete%>-->

  <tbody id="js-tbody-index">
    <% tasks.each do |task| %>
      <tr>
        <% if task.category == "時間が決まったタスク" %>
        <td><%= task.time.strftime("%-H:%M") %></td>
        <% end %>
        <td><%= task.sentence %></td>
        <td><%= link_to 'good', good_task_path(task), method: :patch %><%= task.good %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/by_chance.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', task: @task %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>たまたまやったタスク</h2>
      <%= render 'index', tasks: @tasks %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', time_path %>

app/views/tasks/every.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', task: @task %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>よくやるタスク</h2>
      <%= render 'index', tasks: @tasks %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/time.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', task: @task %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>時間が決まったタスク</h2>
      <%= render 'index', tasks: @tasks %>
    </div>
  </div>
</div>

app/views/tasks/todo.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', task: @task %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>ToDo</h2>
      <%= render 'index', tasks: @tasks %>
    </div>
  </div>
</div>